apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
spec:
  sync:
    syncOnly:
    - kind: Namespace
      version: v1
    - kind: Service
      version: v1
    - group: networking.k8s.io
      kind: Ingress
      version: v1
    - group: "policy"
      version: "v1"
      kind: "PodDisruptionBudget"
    - group: "storage.k8s.io"
      version: "v1"
      kind: "StorageClass"
