kind: Suite
apiVersion: test.gatekeeper.sh/v1alpha1
metadata:
  name: RestrictPodAnnotations
tests:
- name: restrict-annotations
  template: template.yaml
  constraint: examples/constraint/constraint.yaml
  cases:
  # Key-only ban tests (any value is forbidden)
  - name: key-only-ban-violation
    object: examples/pods/violation-key-only-ban.yaml
    inventory:
    - examples/namespaces/solution-namespace.yaml
    assertions:
    - violations: yes
  # Key-value ban tests (only specific value is forbidden)
  - name: key-value-ban-violation
    object: examples/pods/violation-key-value-ban.yaml
    inventory:
    - examples/namespaces/solution-namespace.yaml
    assertions:
    - violations: yes
  - name: key-value-ban-permitted
    object: examples/pods/permitted-key-value-ban.yaml
    inventory:
    - examples/namespaces/solution-namespace.yaml
    assertions:
    - violations: no
  - name: general-permitted
    object: examples/pods/permitted-general.yaml
    inventory:
    - examples/namespaces/solution-namespace.yaml
    assertions:
    - violations: no
  - name: no-annotations-permitted
    object: examples/pods/permitted-no-annoations.yaml
    inventory:
    - examples/namespaces/solution-namespace.yaml
    assertions:
    - violations: no
  # System namespace tests (should always pass regardless of annotations)
  - name: system-ns-key-only-ban-permitted
    object: examples/pods/violation-key-only-ban.yaml
    inventory:
    - examples/namespaces/system-namespace.yaml
    assertions:
    - violations: no
  - name: system-ns-key-value-ban-permitted
    object: examples/pods/violation-key-value-ban.yaml
    inventory:
    - examples/namespaces/system-namespace.yaml
    assertions:
    - violations: no
  - name: system-ns-general-permitted
    object: examples/pods/permitted-general.yaml
    inventory:
    - examples/namespaces/system-namespace.yaml
    assertions:
    - violations: no
